name: Format using stylua

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: "Format with Stylua"
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.15.1
          args: .
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(core): formatted with stylua"
